server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    pipeline_stages:
      - docker: {}  # parses the JSON log structure from Docker logs

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_image]
        target_label: image
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service

      # Drop overly verbose or unsafe labels (e.g., traefik config, long values)
      - action: labelmap
        regex: __meta_docker_container_label_(env|role|tier|app)

      # Optional: drop containers with no logs
      - source_labels: [__meta_docker_container_log_stream]
        regex: ""
        action: drop
