global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8890']

  - job_name: 'classification-gpu-inference'
    static_configs:
      - targets: ['worker:9464']

  - job_name: 'web-crawler'
    scrape_interval: 5s
    static_configs:
      - targets: ['vv8_worker:9464']
    metrics_path: /metrics

  # Add these job configurations to your existing prometheus.yml file in subsystem 2

  # Login page detection crawler job
  - job_name: 'login-page-detection'
    metrics_path: /metrics
    # Replace with the appropriate IP or hostname if needed
    # If the service is on the same machine but in a different Docker network,
    # you might use host.docker.internal on Windows/Mac
    # For direct access on Linux, you might need to use the actual IP address
    static_configs:
      - targets: ['host.docker.internal:9464']
        labels:
          subsystem: 'login-page-detection'
          service: 'crawler'

  # You can add other scrape configs for related components as needed
  # For example, if you have a separate service that runs VLLM inference:
  - job_name: 'vllm-inference'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9465']  # Adjust port if different
        labels:
          subsystem: 'login-page-detection'
          service: 'vllm-inference'