global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'celery'
    static_configs:
      - targets: ['celery_exporter:9808']
  - job_name: 'vv8-queue'
    static_configs:
      - targets: ['172.17.0.1:9121']  # Redis Exporter's metrics endpoint
 
  
